import type { Product } from "./types";

export const sampleProducts: Product[] = [
  { id: "1", marketplace: "Amazon", account: "Mumbai Seller", sku: "KC-GANESH-01", asin: "B0D7K2M8PX", fnsku: "X004J8V2P9", title: "Antique Gold Ganesh Keychain with Premium Finish", brand: "MMS Creations", mrp: 799, category: "Keychain", image: "https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=120&q=80", updated: "Today, 10:42", source: "0_APPAREL_PIN-KEYCHAIN.xlsm" },
  { id: "2", marketplace: "Flipkart", account: "Account 1", sku: "NK-LAYER-GD", fsn: "NKCGHCGMFRKKU5BG", title: "Gold Plated Layered Necklace for Women", brand: "Zaveri Pearls", mrp: 1499, category: "Necklace", image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=120&q=80", updated: "Today, 09:18", source: "Quality_Check_jewellery_set.csv" },
  { id: "3", marketplace: "Amazon", account: "Bangalore Account", sku: "WC-OM-BR-02", asin: "B0CF2NQ4T1", fnsku: "X003L9K8W2", title: "Handcrafted Om Wind Chime for Home", brand: "CraftAura", mrp: 999, category: "Wind Chime", image: "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?auto=format&fit=crop&w=120&q=80", updated: "Yesterday", source: "2_NECKLACE-WIND_CHIME.xlsm" },
  { id: "4", marketplace: "Flipkart", account: "Account 1", sku: "ER-JHUMKA-12", fsn: "ERGGN7RZP2K4ACQS", title: "Traditional Oxidised Silver Jhumka Earrings", brand: "MMS Creations", mrp: 599, category: "Earring", updated: "Yesterday", source: "Quality_Check_earring.csv" },
  { id: "5", marketplace: "Amazon", account: "Mumbai Seller", sku: "PIN-LOTUS-PK", asin: "B0DJ8P5W3N", title: "Enamel Lotus Lapel Pin, Pink and Gold", brand: "PinStory", mrp: 499, category: "Apparel Pin", image: "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?auto=format&fit=crop&w=120&q=80", updated: "06 Aug 2026", source: "0_APPAREL_PIN-KEYCHAIN.xlsm" },
  { id: "6", marketplace: "Flipkart", account: "Account 2", sku: "BR-PEARL-WH", fsn: "BRCGHW6V5NH2MPTA", title: "Classic White Pearl Bracelet", brand: "Pearl House", mrp: 899, category: "Bracelet", image: "https://images.unsplash.com/photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=120&q=80", updated: "05 Aug 2026", source: "Quality_Check_bangle_bracelet_armlet.csv" },
  { id: "7", marketplace: "Amazon", account: "Mumbai Seller", sku: "KC-CAR-BLK", asin: "B0C7MT5R3Q", fnsku: "X002K1Q9U8", title: "Minimal Black Car Keychain", brand: "DriveMate", mrp: 399, category: "Keychain", updated: "04 Aug 2026", source: "1_KEYCHAIN-NECKLACE.xlsm" },
  { id: "8", marketplace: "Flipkart", account: "Account 1", sku: "PD-HEART-RG", fsn: "PDNGK2CZ8UQF4X9W", title: "Rose Gold Heart Pendant with Chain", brand: "MMS Creations", mrp: 799, category: "Pendant", image: "https://images.unsplash.com/photo-1598560917505-59a3ad559071?auto=format&fit=crop&w=120&q=80", updated: "02 Aug 2026", source: "Quality_Check_pendant_locket.csv" },
];
