import { api } from "../../api/client";
import { DataTable, type Column } from "../../components/DataTable";
import { StatusBadge } from "../../components/StatusBadge";
import type { ConsignmentLine } from "../../types";
import { InlineCellEditor } from "./InlineCellEditor";

export function ConsignmentTable({rows,selected,setSelected,onOpen,onChanged}:{rows:ConsignmentLine[];selected:Set<string>;setSelected:(next:Set<string>)=>void;onOpen:(row:ConsignmentLine)=>void;onChanged:(row:ConsignmentLine)=>void}){async function edit(row:ConsignmentLine,field:string,value:string){const updated=await api<ConsignmentLine>(`/consignment-lines/${row.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({expected_version:row.version,field,value})});onChanged(updated)}const columns:Column<ConsignmentLine>[]=[
{key:"state",label:"Status",render:r=><StatusBadge status={r.workflow_state}/>},{key:"format",label:"Format",render:r=><InlineCellEditor label="Format" value={r.format_key} onSave={v=>edit(r,"format_key",v)}/>},
{key:"sku",label:"SKU",render:r=><code>{r.merchant_sku??"—"}</code>},{key:"identifier",label:"ASIN / FNSKU / FSN",render:r=><span className="identifiers"><span>{r.fnsku||r.fsn||r.asin||"—"}</span><small>{r.fnsku?"FNSKU":r.fsn?"FSN":"ASIN"}</small></span>},
{key:"title",label:"Title",className:"title-col",render:r=><InlineCellEditor label="Title" value={r.title} onSave={v=>edit(r,"title",v)}/>},{key:"brand",label:"Brand",render:r=><InlineCellEditor label="Brand" value={r.brand} onSave={v=>edit(r,"brand",v)}/>},
{key:"mrp",label:"MRP",render:r=><InlineCellEditor label="MRP" type="number" value={r.mrp} onSave={v=>edit(r,"mrp_override",v)}/>},{key:"mrps",label:"MRP Source",render:r=><small className="source-chip">{r.mrp_source}</small>},
{key:"net",label:"Net Qty",render:r=><span className="quantity-edit"><InlineCellEditor label="Net quantity" type="number" value={r.net_quantity_value} onSave={v=>edit(r,"net_quantity_value",v)}/><InlineCellEditor label="Net unit" value={r.net_quantity_unit} onSave={v=>edit(r,"net_quantity_unit",v)}/></span>},
{key:"print",label:"Print Qty",render:r=><InlineCellEditor label="Print quantity" type="number" value={r.print_quantity} onSave={v=>edit(r,"print_quantity",v)}/>},{key:"match",label:"Match",render:r=><span>{r.match_method??r.match_status}</span>},{key:"error",label:"Error",render:r=>r.error_count?<span className="issue-count" title={r.issue_codes.join(", ")}>{r.error_count} blocking</span>:<span className="muted">None</span>},
];async function toggle(id:string){const next=new Set(selected);next.has(id)?next.delete(id):next.add(id);setSelected(next);await api("/consignment-lines/bulk-select",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({consignment_id:rows[0]?.consignment_id,line_ids:[id],selected:next.has(id)})})}async function toggleAll(){const visible=rows.map(r=>r.id),all=visible.every(id=>selected.has(id));const next=new Set(selected);visible.forEach(id=>all?next.delete(id):next.add(id));setSelected(next);if(rows.length)await api("/consignment-lines/bulk-select",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({consignment_id:rows[0].consignment_id,line_ids:visible,selected:!all})})}return <DataTable rows={rows} columns={columns} selected={selected} toggle={id=>void toggle(id)} toggleAll={()=>void toggleAll()} onRow={onOpen}/>}
