import { useEffect, useState } from "react";
import { PanelRightClose } from "lucide-react";
import { api } from "../../api/client";
import { LoadingSkeleton } from "../../components/States";
import { StatusBadge } from "../../components/StatusBadge";
import type { PrintJob } from "../../types";

const tabs=["Overview","Lines","Snapshot","Events"] as const;
export function PrintJobDrawer({job,onClose,onChanged}:{job:PrintJob;onClose:()=>void;onChanged:()=>void}){const[detail,setDetail]=useState<any>(null),[tab,setTab]=useState<typeof tabs[number]>("Overview"),[error,setError]=useState("");useEffect(()=>{api(`/print-jobs/${job.id}`).then(setDetail).catch(e=>setError(e.message))},[job.id]);async function simulate(){try{await api(`/print-jobs/${job.id}/simulate-success`,{method:"POST"});onChanged();onClose()}catch(e:any){setError(e.message)}}async function reprint(){try{await api(`/print-jobs/${job.id}/reprint`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({})});onChanged();onClose()}catch(e:any){setError(e.message)}}return <><button className="backdrop" onClick={onClose} aria-label="Close print job"/><aside className="drawer product-drawer"><header><div><p>PRINT JOB</p><h2>{job.id.slice(0,8)}</h2></div><button className="icon-button" onClick={onClose}><PanelRightClose size={20}/></button></header><div className="drawer-tabs">{tabs.map(item=><button key={item} className={tab===item?"active":""} onClick={()=>setTab(item)}>{item}</button>)}</div><div className="drawer-body">{error&&<p className="inline-error">{error}</p>}{!detail?<LoadingSkeleton/>:tab==="Overview"?<><dl><div><dt>Status</dt><dd><StatusBadge status={detail.status}/></dd></div><div><dt>Marketplace</dt><dd>{detail.marketplace}</dd></div><div><dt>Rows</dt><dd>{detail.rows}</dd></div><div><dt>Labels</dt><dd>{detail.labels}</dd></div><div><dt>Prepared</dt><dd>{new Date(detail.created_at).toLocaleString()}</dd></div><div><dt>Transport</dt><dd>Printer Agent — Phase 3</dd></div></dl>{detail.status==="completed"?<button className="primary" onClick={()=>void reprint()}>Reprint Exact Snapshot</button>:detail.simulation_enabled&&<button className="simulation-button" onClick={()=>void simulate()}>SIMULATION · Successful Print</button>}</>:tab==="Lines"?<div className="job-lines">{detail.lines.map((line:any)=><div key={line.id}><code>{line.snapshot.sku||line.snapshot.fsn}</code><span>{line.copies} copies</span><StatusBadge status={line.status}/></div>)}</div>:tab==="Snapshot"?<pre className="snapshot-view">{JSON.stringify(detail.lines.map((line:any)=>line.snapshot),null,2)}</pre>:<div className="history-list">{detail.events.map((event:any)=><div key={event.id}><i/><span><strong>{event.type}</strong><p>{JSON.stringify(event.payload)}</p><small>{new Date(event.created_at).toLocaleString()}</small></span></div>)}</div>}</div></aside></>}
