import { useEffect, useState } from "react";
import { api, queryString } from "../../api/client";
import { DataTable, type Column } from "../../components/DataTable";
import { EmptyState, LoadingSkeleton } from "../../components/States";
import { StatusBadge } from "../../components/StatusBadge";
import type { Account, PrintJob } from "../../types";
import { PrintJobDrawer } from "./PrintJobDrawer";

export function PrintQueuePage(){const[jobs,setJobs]=useState<PrintJob[]>([]),[accounts,setAccounts]=useState<Account[]>([]),[status,setStatus]=useState(""),[marketplace,setMarketplace]=useState(""),[account,setAccount]=useState(""),[loading,setLoading]=useState(true),[active,setActive]=useState<PrintJob|null>(null),[simulation,setSimulation]=useState(false);function load(){setLoading(true);api<any>(`/print-jobs?${queryString({status,marketplace,account_id:account})}`).then(data=>{setJobs(data.items);setSimulation(data.simulation_enabled)}).finally(()=>setLoading(false))}useEffect(()=>{api<Account[]>("/accounts").then(setAccounts)},[]);useEffect(load,[status,marketplace,account]);const columns:Column<PrintJob>[]=[{key:"id",label:"Job ID",render:r=><code>{r.id.slice(0,8)}</code>},{key:"status",label:"Status",render:r=><><StatusBadge status={r.status}/>{r.simulation&&<small className="simulation-chip">SIMULATION</small>}</>},{key:"marketplace",label:"Marketplace",render:r=>r.marketplace},{key:"account",label:"Account",render:r=>accounts.find(a=>a.id===r.account_id)?.name??r.account_id.slice(0,8)},{key:"consignment",label:"Consignment",render:r=><code>{r.consignment_id?.slice(0,8)??"—"}</code>},{key:"printer",label:"Printer Profile",render:r=>r.printer_name??"Not assigned"},{key:"rows",label:"Rows",render:r=>r.rows},{key:"labels",label:"Labels",render:r=>r.labels},{key:"created",label:"Created",render:r=>new Date(r.created_at).toLocaleString()},{key:"updated",label:"Last Updated",render:r=>new Date(r.updated_at).toLocaleString()}];return <section className="content"><div className="page-heading"><div><span className="eyebrow">PRINT OPERATIONS</span><h1>Print Queue</h1><p>Immutable prepared jobs. Actual printer transport arrives with the local agent in Phase 3.</p></div>{simulation&&<span className="simulation-banner">SIMULATION ENABLED · DEVELOPMENT ONLY</span>}</div><div className="toolbar"><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{["draft","ready","waiting_for_agent","completed","failed","cancelled"].map(x=><option key={x}>{x}</option>)}</select><select value={marketplace} onChange={e=>setMarketplace(e.target.value)}><option value="">All marketplaces</option><option value="amazon">Amazon</option><option value="flipkart">Flipkart</option></select><select value={account} onChange={e=>setAccount(e.target.value)}><option value="">All accounts</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></div>{loading?<LoadingSkeleton/>:jobs.length?<DataTable rows={jobs} columns={columns} selected={new Set()} toggle={()=>{}} toggleAll={()=>{}} onRow={setActive}/>:<EmptyState title="No prepared jobs" detail="Select valid consignment rows and prepare a print job. Preparation does not mean Printed."/>}{active&&<PrintJobDrawer job={{...active,simulation_enabled:simulation} as any} onClose={()=>setActive(null)} onChanged={load}/>}</section>}
