import { useEffect, useState } from "react";
import { ChevronLeft, ChevronRight, ExternalLink, PanelRightClose, ZoomIn } from "lucide-react";
import { api } from "../../api/client";
import { EmptyState, ErrorState, LoadingSkeleton } from "../../components/States";
import { IdentifierCopy } from "../../components/IdentifierCopy";
import { StatusBadge } from "../../components/StatusBadge";
import type { Product } from "../../types";

const tabs=["Overview","Images","Label Data","Print History","Change History"] as const;
type Tab=typeof tabs[number];

export function ProductDrawer({product,close}:{product:Product;close:()=>void}){const[tab,setTab]=useState<Tab>("Overview");const[history,setHistory]=useState<any[]|null>(null);const[printHistory,setPrintHistory]=useState<any[]|null>(null);const[error,setError]=useState("");const[lightbox,setLightbox]=useState<number|null>(null);const ids=Object.fromEntries(product.identifiers.map(i=>[i.kind,i.value]));
useEffect(()=>{setError("");if(tab==="Change History"&&history===null)api<any[]>(`/products/${product.id}/audit`).then(setHistory).catch(e=>setError(e.message));if(tab==="Print History"&&printHistory===null)api<any[]>(`/products/${product.id}/print-history`).then(setPrintHistory).catch(e=>setError(e.message));},[tab,product.id,history,printHistory]);
return <><button className="backdrop" onClick={close} aria-label="Close product drawer"/><aside className="drawer product-drawer"><header><div><p>PRODUCT</p><h2>{product.sku??"No SKU"}</h2></div><button className="icon-button" onClick={close}><PanelRightClose size={20}/></button></header><div className="drawer-tabs">{tabs.map(item=><button className={tab===item?"active":""} onClick={()=>setTab(item)} key={item}>{item}</button>)}</div><div className="drawer-body">{error&&<ErrorState message={error}/>} {tab==="Overview"&&<><div className="drawer-title"><span className={`badge ${product.account.marketplace}`}><b>{product.account.marketplace[0]}</b>{product.account.marketplace}</span><h3>{product.title??"Untitled product"}</h3><p>{product.account.name}</p></div><div className="identifier-grid"><IdentifierCopy label="SKU" value={product.sku}/><IdentifierCopy label="ASIN" value={ids.asin}/><IdentifierCopy label="FNSKU" value={ids.fnsku}/><IdentifierCopy label="FSN" value={ids.fsn}/><IdentifierCopy label="Listing ID" value={ids.listing_id}/></div><dl><div><dt>Brand</dt><dd>{product.brand??"—"}</dd></div><div><dt>MRP</dt><dd>{product.mrp?`₹${Number(product.mrp).toLocaleString("en-IN")}`:"Not provided"}</dd></div><div><dt>Category / Format</dt><dd>{product.category??"—"}</dd></div><div><dt>Source template</dt><dd>{product.source_template??"—"}</dd></div><div><dt>Source file</dt><dd>{product.source_file??"—"}</dd></div><div><dt>Created</dt><dd>{new Date(product.created_at).toLocaleString()}</dd></div><div><dt>Last updated</dt><dd>{new Date(product.updated_at).toLocaleString()}</dd></div></dl></>}
{tab==="Images"&&<ImageGallery product={product} lightbox={lightbox} setLightbox={setLightbox}/>} {tab==="Label Data"&&<LabelData product={product}/>} {tab==="Print History"&&(printHistory===null?<LoadingSkeleton/>:printHistory.length?<HistoryRows items={printHistory}/>:<EmptyState title="No print history" detail="Print jobs will appear here after the print-agent phase."/>)} {tab==="Change History"&&(history===null?<LoadingSkeleton/>:history.length?<HistoryRows items={history}/>:<EmptyState title="No changes recorded" detail="Imported and manual field changes will appear here."/>)}</div></aside>{lightbox!==null&&<div className="lightbox"><button onClick={()=>setLightbox(null)}>×</button><button onClick={()=>setLightbox((lightbox-1+product.images.length)%product.images.length)}><ChevronLeft/></button><img src={product.images[lightbox].cached_url||product.images[lightbox].url} alt="Product"/><button onClick={()=>setLightbox((lightbox+1)%product.images.length)}><ChevronRight/></button></div>}</>}

function ImageGallery({product,lightbox,setLightbox}:{product:Product;lightbox:number|null;setLightbox:(n:number|null)=>void}){const[requested,setRequested]=useState(false);if(!product.images.length)return <div><EmptyState title="No image available" detail="No imported or cached marketplace image is stored."/><button className="primary center-button" disabled={requested} onClick={()=>{setRequested(true);api(`/images/products/${product.id}/enrichment`,{method:"POST"})}}>{requested?"Enrichment requested":"Request image enrichment"}</button></div>;return <div className="image-gallery"><div className="main-image"><img src={product.images[0].cached_url||product.images[0].url} alt="Main product"/><button onClick={()=>setLightbox(0)}><ZoomIn size={16}/>View</button></div><div className="image-thumbnails">{product.images.map((image,index)=><button key={image.id} onClick={()=>setLightbox(index)}><img src={image.cached_url||image.url} alt={`${image.kind} ${index+1}`}/><span>{image.kind} · {image.source}</span><StatusBadge status={image.status}/></button>)}</div><a className="original-link" href={product.images[0].url} target="_blank" rel="noreferrer"><ExternalLink size={14}/>Open original image</a></div>}
function LabelData({product}:{product:Product}){const[status,setStatus]=useState("");async function save(mode:"catalog"|"consignment",form:HTMLFormElement){setStatus("Saving…");const values=Object.fromEntries(new FormData(form).entries());const fields={...values,mrp:values.mrp?Number(values.mrp):null,net_quantity:values.net_quantity?Number(values.net_quantity):null};try{await api(`/products/${product.id}/label-data?mode=${mode}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({fields})});setStatus(mode==="catalog"?"Catalog updated and audited":"Prepared for this consignment only")}catch(e:any){setStatus(e.message)}}return <form className="label-form"><label>Format<input name="category" defaultValue={product.category??""}/></label><label>Brand<input name="brand" defaultValue={product.brand??""}/></label><label>Model name<input name="model_name" defaultValue={String(product.extra_attributes.model_name??"")}/></label><label>Model number<input name="model_number" defaultValue={String(product.extra_attributes.model_number??"")}/></label><label>Color<input name="color" defaultValue={String(product.extra_attributes.color??"")}/></label><div className="split-fields"><label>Net quantity<input name="net_quantity" type="number" min="1" defaultValue={String(product.extra_attributes.net_quantity??1)}/></label><label>MRP<input name="mrp" type="number" defaultValue={product.mrp}/></label></div><label>Address profile<select name="address_profile_id"><option value="">Select profile…</option></select></label><div className="safe-save"><button type="button" className="secondary" onClick={e=>save("consignment",e.currentTarget.form!)}>Use for this consignment</button><button type="button" className="primary" onClick={e=>save("catalog",e.currentTarget.form!)}>Update catalog</button></div><p>{status||"Catalog updates create an audit event."}</p></form>}
function HistoryRows({items}:{items:any[]}){return <div className="history-list">{items.map((item,index)=><div key={item.id??index}><i/><span><strong>{item.action??item.result??"Print job"}</strong><p>{item.changes?JSON.stringify(item.changes):`${item.copies} copies · ${item.printer??"Printer pending"}`}</p><small>{new Date(item.created_at??item.printed_at).toLocaleString()}</small></span></div>)}</div>}
