import { useEffect, useState } from "react";
import { FileSpreadsheet, UploadCloud } from "lucide-react";
import { api } from "../../api/client";
import { EmptyState, ErrorState, LoadingSkeleton } from "../../components/States";
import { StatusBadge } from "../../components/StatusBadge";
import type { Account, ImportPreview } from "../../types";

export function ImportsPage(){const[accounts,setAccounts]=useState<Account[]>([]),[accountId,setAccountId]=useState(""),[files,setFiles]=useState<File[]>([]),[previews,setPreviews]=useState<ImportPreview[]>([]),[history,setHistory]=useState<any[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState("");useEffect(()=>{api<Account[]>("/accounts").then(setAccounts);api<any[]>("/imports").then(setHistory).catch(()=>{})},[]);const account=accounts.find(a=>a.id===accountId);async function preview(){if(!account||!files.length)return;setLoading(true);setError("");const form=new FormData();form.set("marketplace",account.marketplace);form.set("account_id",account.id);files.forEach(file=>form.append("files",file));try{setPreviews(await api<ImportPreview[]>("/imports/preview",{method:"POST",body:form}))}catch(e:any){setError(e.message)}finally{setLoading(false)}}
return <section className="content"><div className="page-heading"><div><p className="eyebrow">CATALOG</p><h1>Import Center</h1><p>Preview mappings, formula issues, sheets, and duplicate file fingerprints before importing.</p></div></div><div className="section-tabs"><button className="active">New Import</button><button>Import History</button><button>Catalog Batches</button></div><div className="import-setup"><label>Seller account<select value={accountId} onChange={e=>setAccountId(e.target.value)}><option value="">Select account…</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.marketplace} · {a.name}</option>)}</select></label><label className="dropzone"><input type="file" multiple accept=".csv,.xlsx,.xlsm" onChange={e=>setFiles(Array.from(e.target.files??[]))}/><UploadCloud size={30}/><strong>Drop Amazon or Flipkart catalog files</strong><span>CSV, XLSX, XLSM · multiple files supported</span></label><button className="primary" disabled={!account||!files.length||loading} onClick={preview}>Preview {files.length||""} file{files.length===1?"":"s"}</button></div>{loading&&<LoadingSkeleton/>}{error&&<ErrorState message={error}/>} {!!previews.length&&<div className="import-card"><header><strong>Import preview</strong><button className="primary" disabled={previews.some(p=>p.mapping_status==="blocked")}>Import {previews.length>1?"batch":"file"}</button></header><table><thead><tr><th>File</th><th>Sheet</th><th>Detected Type</th><th>Rows</th><th>Header</th><th>Mapping</th><th>Warnings</th></tr></thead><tbody>{previews.map(p=><tr key={p.file}><td><div className="file-cell"><FileSpreadsheet size={17}/><strong>{p.file}</strong>{p.previously_imported&&<small>Previously imported</small>}</div></td><td>{p.sheet}</td><td>{p.detected_type}</td><td>{p.rows.toLocaleString()}</td><td>Row {p.header_row}</td><td><StatusBadge status={p.mapping_status}/></td><td>{p.warnings.length?p.warnings.join(" · "):"—"}</td></tr>)}</tbody></table></div>}<h2 className="section-heading">Import history</h2>{!history.length?<EmptyState title="No imports yet" detail="Completed catalog imports will appear here."/>:<div className="table-card"><table><thead><tr><th>Import ID</th><th>Date</th><th>Source</th><th>Sheet</th><th>Rows</th><th>New</th><th>Updated</th><th>Unchanged</th><th>Errors</th><th>Status</th></tr></thead><tbody>{history.map(item=><tr key={item.id}><td><code>{item.id.slice(0,8)}</code></td><td>{new Date(item.date).toLocaleString()}</td><td>{item.source_file}</td><td>{item.sheet}</td><td>{item.rows}</td><td>{item.new}</td><td>{item.updated}</td><td>{item.unchanged}</td><td>{item.errors}</td><td><StatusBadge status={item.status}/></td></tr>)}</tbody></table></div>}</section>}
